stages:
    - build
    - deploy

build client:
    image: node
    stage: build
    script:
        - yarn install --pure-lockfile --cache-folder .yarn
        - npm run docs:build

    artifacts:
        expire_in: 1 week
        paths:
            - docs

deploy:
    image: alpine
    stage: deploy
    script:
        - 'which ssh-agent || ( apk update && apk add --no-cache rsync openssh-client )'
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_KEY" | ssh-add -
        - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        - rsync -rav docs/.vitepress/dist/  $SERVER_USER@$SERVER_IP:/home/opc/Projects/jhc/public
    only:
        - master
